###################
# ENV VARS:
# - PAT (generated at Personal Access Tokens - with workflow access checked)
###################

name: Create new release manually

on:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch release version
        id: fetch-version
        run: |
          curl -sL https://api.npms.io/v2/package/n8n | jq -r ".collected.metadata.version" > release-versions/n8n-latest.txt
          echo ::set-output name=version::$(cat release-versions/n8n-latest.txt)

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New manual release v${{steps.fetch-version.outputs.version}}