###################
# ENV VARS:
# - FULL_NAME
# - EMAIL
# - REPO_SCOPED_TOKEN (by default)
###################

name: Check new release
on:
  schedule:
    - cron: "0 */1 * * *"
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.npms.io/v2/package/n8n | jq -r ".collected.metadata.version" > release-versions/n8n-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name '${{ secrets.FULL_NAME }}'
          git config --global user.email '${{ secrets.EMAIL }}'
          git commit -am "New release: $(cat release-versions/n8n-latest.txt)"
          git push